import { createHmac } from 'node:crypto';

import { describe, expect, it } from 'vitest';

import { readDelivery } from '../nodes/ComersTrigger/envelope';
import { authenticateDelivery } from '../nodes/ComersTrigger/signature';

/**
 * One delivery, pinned as a hand-checked snapshot of what the Core Events
 * dispatcher sends.
 *
 * Every other test in this package builds its request from the same helpers the
 * assertions read back, which makes them self-consistent and blind: a fixture
 * that drifts from the real sender still passes, because both halves drifted
 * together. That is how two mismatches reached a published release — an event
 * key of `support.case.opened` where the catalog says
 * `comers.core.support.case.opened`, and a first attempt numbered 0 where the
 * dispatcher numbers it 1.
 *
 * So this one is written out literally rather than generated, and it is the
 * only place in the suite where the expected bytes appear by hand.
 *
 * What it does and does not do, stated plainly:
 *
 *   It pins this package to a snapshot of the contract that was read and
 *   verified by hand against the Core Events sources at the commit named below,
 *   and it fails when this package drifts from that snapshot — a helper edited,
 *   a validation loosened, a field renamed on the way out.
 *
 *   It does NOT watch the Core Events repository. Nothing here can. If Core
 *   Events changes what it puts on the wire, this test keeps passing until a
 *   person updates the snapshot. Real cross-repository drift is caught by an
 *   end-to-end run against a live dispatcher, or one day by a contract artefact
 *   both sides consume — not by a file only this repository can change.
 *
 * Verified by hand against comers-core-events at
 * c55d100add4a203e8a61efb94008fb7e36ca8c05 (main), in:
 *
 *   src/modules/catalog/event-catalog.ts
 *     the event key, its version, its producer and its subject type
 *
 *   src/modules/dispatcher/delivery-dispatcher.service.ts
 *     `envelope()` — the body's shape, including `specVersion: "comers.v1"`
 *     and `sequence` as a decimal string rather than a JSON number
 *     the `headers` object — the full header set, and the fact that
 *     `X-Correlation-ID` appears only when a correlation id exists
 *     `String(delivery.attempt)` — the attempt, raised to 1 by the claim in
 *     `delivery.repository.ts` before the row is read back
 *
 *   src/modules/dispatcher/delivery-signature.ts
 *     `HMAC-SHA256(secret, "v1:<timestamp>:<raw body>")`, base64, offered as
 *     `v1=<signature>`
 *
 * Nothing here imports from that repository: this package has no dependency on
 * it, at build time or run time.
 */

const SIGNING_MATERIAL = 'IM68OKPZoDziE_Qss65qwKTNRYQTE1uc9hwsc0e1uGQ';
const TIMESTAMP = 1788259530;

/** The exact bytes the dispatcher would put on the wire. */
const RAW_BODY = Buffer.from(
	'{"specVersion":"comers.v1","eventId":"0199c3f0-1a2b-7c3d-8e4f-000000000001",' +
		'"eventKey":"comers.core.support.case.opened","eventVersion":1,' +
		'"sequence":"9007199254740993","occurredAt":"2026-09-11T07:05:30.000Z",' +
		'"producer":"comers-core-support",' +
		'"scope":{"organizationId":"0199c3f0-1a2b-7c3d-8e4f-00000000000a","sellerId":null,"sellerStoreId":null},' +
		'"subject":{"type":"support_case","id":"0199c3f0-1a2b-7c3d-8e4f-00000000000b"},' +
		'"correlationId":"0199c3f0-1a2b-7c3d-8e4f-00000000000c",' +
		'"data":{"caseId":"0199c3f0-1a2b-7c3d-8e4f-00000000000b","priority":"high"}}',
	'utf8',
);

/**
 * The signature Core Events produced for exactly these bytes, copied from the
 * `canonical` entry of `fixtures/contract-vectors.json`, which was generated by
 * running that repository's own `signDelivery`.
 *
 * Written out as a literal so the snapshot pins the expected *result* of
 * signing, not only the rule. A test that recomputes the signature and then
 * checks its own arithmetic would still pass if the rule itself were wrong.
 */
const SIGNATURE = 'SuL83GxdJ0yc9mllsUjnWr/KpSwnWRhBaJIOiZPk+rM=';

/** The full header set, in the casing the dispatcher uses. */
const HEADERS: Record<string, string> = {
	'content-type': 'application/json',
	'X-Comers-Event-Id': '0199c3f0-1a2b-7c3d-8e4f-000000000001',
	'X-Comers-Event-Key': 'comers.core.support.case.opened',
	'X-Comers-Event-Version': '1',
	'X-Comers-Subscription-Id': '0199c3f0-1a2b-7c3d-8e4f-000000000002',
	'X-Comers-Delivery-Id': '0199c3f0-1a2b-7c3d-8e4f-000000000003',
	'X-Comers-Delivery-Attempt': '1',
	'X-Comers-Timestamp': String(TIMESTAMP),
	'X-Comers-Signature': `v1=${SIGNATURE}`,
	'X-Correlation-ID': '0199c3f0-1a2b-7c3d-8e4f-00000000000c',
};

describe('a delivery exactly as the Core Events dispatcher sends it', () => {
	it('carries the signature Core Events produced for these bytes', () => {
		// An independent recomputation, so the literal above is checked rather
		// than merely trusted — and if the two ever disagree, the rule and the
		// recorded result have parted company.
		expect(
			createHmac('sha256', SIGNING_MATERIAL)
				.update(`v1:${TIMESTAMP}:${RAW_BODY.toString('utf8')}`, 'utf8')
				.digest('base64'),
		).toBe(SIGNATURE);
	});

	it('authenticates', () => {
		expect(
			authenticateDelivery({
				method: 'POST',
				headers: HEADERS,
				rawBody: RAW_BODY,
				secret: SIGNING_MATERIAL,
				nowSeconds: TIMESTAMP,
			}),
		).toEqual({ authenticated: true, timestamp: TIMESTAMP });
	});

	it('reads as one item, with the catalog key and the first attempt', () => {
		const result = readDelivery({ headers: HEADERS, rawBody: RAW_BODY, timestamp: TIMESTAMP });

		expect(result.ok).toBe(true);
		expect(result.ok && result.item.event.eventKey).toBe('comers.core.support.case.opened');
		expect(result.ok && result.item.event.eventVersion).toBe(1);
		expect(result.ok && result.item.event.producer).toBe('comers-core-support');
		expect(result.ok && (result.item.event.subject as { type: string }).type).toBe('support_case');
		expect(result.ok && result.item.delivery.deliveryAttempt).toBe(1);
	});

	it('keeps sequence a decimal string, because the column is a bigint', () => {
		const result = readDelivery({ headers: HEADERS, rawBody: RAW_BODY, timestamp: TIMESTAMP });

		expect(result.ok && result.item.event.sequence).toBe('9007199254740993');
		// Past 2^53-1: a JSON number would not survive the round trip.
		expect(String(Number('9007199254740993'))).not.toBe('9007199254740993');
	});

	it('hands the envelope over as it parsed, field for field', () => {
		const result = readDelivery({ headers: HEADERS, rawBody: RAW_BODY, timestamp: TIMESTAMP });

		expect(result.ok && result.item.event).toEqual(JSON.parse(RAW_BODY.toString('utf8')));
	});

	it('would refuse the same delivery numbered 0', () => {
		// One of the two mismatches this file exists to catch: no claim
		// produces a 0.
		expect(
			readDelivery({
				headers: { ...HEADERS, 'X-Comers-Delivery-Attempt': '0' },
				rawBody: RAW_BODY,
				timestamp: TIMESTAMP,
			}),
		).toEqual({ ok: false, reason: 'malformed_delivery_headers' });
	});

	it('would refuse a header naming a different event than the signed body', () => {
		// The other one: the shortened key is not what the catalog defines.
		expect(
			readDelivery({
				headers: { ...HEADERS, 'X-Comers-Event-Key': 'support.case.opened' },
				rawBody: RAW_BODY,
				timestamp: TIMESTAMP,
			}),
		).toEqual({ ok: false, reason: 'headers_contradict_envelope' });
	});
});

describe('the dispatcher omits X-Correlation-ID when there is no correlation id', () => {
	// `...(delivery.correlationId ? { "X-Correlation-ID": … } : {})` — the header
	// is conditional, but `correlationId` is always present in the body, as null.
	const body = Buffer.from(
		RAW_BODY.toString('utf8').replace(
			'"correlationId":"0199c3f0-1a2b-7c3d-8e4f-00000000000c"',
			'"correlationId":null',
		),
		'utf8',
	);
	const signature = createHmac('sha256', SIGNING_MATERIAL)
		.update(`v1:${TIMESTAMP}:${body.toString('utf8')}`, 'utf8')
		.digest('base64');
	const headers: Record<string, string> = {
		...HEADERS,
		'X-Comers-Signature': `v1=${signature}`,
	};
	delete headers['X-Correlation-ID'];

	it('is still a complete delivery', () => {
		const result = readDelivery({ headers, rawBody: body, timestamp: TIMESTAMP });

		expect(result.ok).toBe(true);
		expect(result.ok && result.item.event.correlationId).toBeNull();
	});
});

describe('forward compatibility survives the stricter checks', () => {
	const deliver = (rawBody: Buffer, overrides: Record<string, string> = {}) => {
		const signature = createHmac('sha256', SIGNING_MATERIAL)
			.update(`v1:${TIMESTAMP}:${rawBody.toString('utf8')}`, 'utf8')
			.digest('base64');

		return {
			headers: { ...HEADERS, 'X-Comers-Signature': `v1=${signature}`, ...overrides },
			rawBody,
			timestamp: TIMESTAMP,
		};
	};

	it('accepts an event key no catalog entry mentions today', () => {
		const body = Buffer.from(
			RAW_BODY.toString('utf8').replace(
				'comers.core.support.case.opened',
				'comers.core.orders.shipment.dispatched',
			),
			'utf8',
		);
		const result = readDelivery(
			deliver(body, { 'X-Comers-Event-Key': 'comers.core.orders.shipment.dispatched' }),
		);

		expect(result.ok).toBe(true);
		expect(result.ok && result.item.event.eventKey).toBe(
			'comers.core.orders.shipment.dispatched',
		);
	});

	it('accepts a signature scheme it does not know beside the one it does', () => {
		expect(
			authenticateDelivery({
				method: 'POST',
				headers: {
					...HEADERS,
					'X-Comers-Signature': `v2=ZGVmaW5pdGVseS1ub3QtdjE=,v1=${SIGNATURE}`,
				},
				rawBody: RAW_BODY,
				secret: SIGNING_MATERIAL,
				nowSeconds: TIMESTAMP,
			}).authenticated,
		).toBe(true);
	});
});
